### ISSUE TITLE
Download task fails on arm, still tries think is x86_64

### ISSUE THREAD

**Issue by SeanChristopherConway** [itwars/k3s-ansible#2]
`fatal: [10.0.0.109]: FAILED! => {"msg": "The conditional check '( ansible_facts.userspace_architecture == \"x86_64\" )' failed. The error was: error while evaluating conditional (( ansible_facts.userspace_architecture == \"x86_64\" )):`

How do I use this to intall on arm. I am fairly new to ansible so please forgive me if I have missed something obvious. Thanks.

**Comment by itwars** [comment]
I'll dive into it next weekend! Stay tune :)

**Comment by ghost** [comment]
I have a patch for this, will create a PR

**Comment by itwars** [comment]
OK I've fixed it!
