### ISSUE TITLE
Warning using dashes in group names

### ISSUE THREAD

**Issue by PieBru** [itwars/k3s-ansible#4]
Hi Vincent, just a silly note.
It seems ansible 2.8.4 doesn't like the dash in the cluster name (host.ini).

```
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{'-'}" in group name (k3s-cluster)
```

Thanks for your great playbook,
Piero

**Comment by itwars** [comment]
Thank's I will check it in few days!
