### ISSUE TITLE
how to use/install this role?

### ISSUE THREAD

**Issue by thelittlebug** [itwars/k3s-ansible#7]
hi,

i've tried to install this role with ansible-galaxy:
`ansible-galaxy install git+https://github.com/itwars/k3s-ansible`

and get this error:
```
[WARNING]: - k3s-ansible was NOT installed successfully: this role does not appear to have a meta/main.yml file.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

```

**Comment by itwars** [comment]
Huum, I need to add ansible galaxy meta file!
I’ll do it this evening.

**Comment by itwars** [comment]
Hello Herbert,
I've just fixe it: 9cbe31a28dd39bb072ff33b1d617e4bc4d834988
Enjoy!
